package de.fileinputstream.uuidcache.event;


import org.bukkit.event.Cancellable;
import org.bukkit.event.Event;
import org.bukkit.event.HandlerList;

/**
 * This class has been generated by Alexander on 30.04.18 20:33
 * You are not allowed to edit this resource or other components of it
 * © 2018 Alexander Fiedler
 */
public class UUIDCachedEvent extends Event implements Cancellable {

    public UUIDCachedEvent(String playerName, String cachedUUID) {
        this.playerName = playerName;
        this.cachedUUID = cachedUUID;
    }
    String playerName;
    String cachedUUID;
    boolean cancelled;
    @Override
    public boolean isCancelled() {
        return cancelled;
    }

    @Override
    public void setCancelled(boolean b) {
        cancelled = b;
    }

    @Override
    public HandlerList getHandlers() {
        return null;
    }

    @Override
    public String getEventName() {
        return super.getEventName();
    }

    public String getCachedUUID() {
        return cachedUUID;
    }

    public String getPlayerName() {
        return playerName;
    }
}
