package de.fileinputstream.uuidcache.redis;

import redis.clients.jedis.Jedis;

/**
 * This class has been generated by Alexander on 29.04.18 22:02
 * You are not allowed to edit this resource or other components of it
 * © 2018 Alexander Fiedler
 */
public class RedisManager {

    public Jedis jedis;

    /**
     * Connects to the redis database with host and port.
     * @param host
     * @param port
     */
    public void connectToRedis(String host, int port) {
        jedis = new Jedis(host,port);
        System.out.println("Connected to redis server at " + host + ":" + port + " using password: no");
    }

    /**
     * Connects to the redis database with host, port and password.
     * @param host
     * @param port
     * @param password
     */
    public void connectToRedis(String host, int port, String password) {
        jedis = new Jedis(host,port);
        jedis.auth(password);
        System.out.println("Connected to redis server at " + host + ":" + port + " using password: yes");
    }

    public Jedis getJedis() {
        return jedis;
    }
}
