package de.fileinputstream.uuidcache.cache.backends;

import java.io.Serializable;

/**
 * This class has been generated by Alexander on 29.04.18 22:23
 * You are not allowed to edit this resource or other components of it
 * © 2018 Alexander Fiedler
 */
public interface Backend {

    boolean isAvailable();

}
