package de.fileinputstream.uuidcache.meta;

import com.sun.istack.internal.Nullable;
import io.netty.channel.Channel;

import java.util.ArrayList;

/**
 * This class has been generated by Alexander on 02.05.18 16:53
 * You are not allowed to edit this resource or other components of it
 * © 2018 Alexander Fiedler
 */
public class PlayerMetadata extends ArrayList<Object> {
    /**
     * This class represents an simple ArrayList object. It is used as data delivery.
     */

    private static final long serialVersionUID = 8501296964229015349L;

    @Nullable
    public Channel dataSender;

    public PlayerMetadata(String decName, Object... contents) {
        this.add(0, decName);
        for (Object wrappedDataPackageContents : contents) {
            this.add(wrappedDataPackageContents);
        }
    }

    /**
     * Returns the id of the WrappedData. The id has to be a string. Otherwise, the compiler will throw an {@link IllegalArgumentException}
     *
     * @return String
     * @throws IllegalArgumentException
     */
    public String getID() {
        if (!(this.get(0) instanceof String)) {
            throw new IllegalArgumentException("Declaration name is not a String.");
        }
        return (String) this.get(0);
    }
}
