package de.fileinputstream.uuidcache.meta;

/**
 * This class has been generated by Alexander on 02.05.18 16:58
 * You are not allowed to edit this resource or other components of it
 * © 2018 Alexander Fiedler
 */
public class PlayerMetaManager {
}
