package de.fileinputstream.uuidcache.cache;

import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class has been generated by Alexander on 29.04.18 22:17
 * You are not allowed to edit this resource or other components of it
 * © 2018 Alexander Fiedler
 */
public enum UUIDBackend {

    MINETOOLS("MINETOOLS","https://api.minetools.eu/");
    String name;
    String address;


    private UUIDBackend(String name, String address) {
        this.name = name;
        this.address = address;
    }

    public String getName() {
        return name;
    }

    public String getAddress() {
        return address;
    }

    public boolean isReachable() {
        try {
            URL url = new URL(getAddress());
            try {
                final InputStream stream = url.openStream();
                return true;
            } catch (IOException e) {
                return false;
            }
        } catch (MalformedURLException e) {
            return false;

        }
    }

    public static UUIDBackend getUUIDBackendByName(final String name) {
        for(UUIDBackend backends : values()) {
            if(backends.getName().equalsIgnoreCase(name)) {
                return backends;
            }
        }
        return null;
    }

}
