package de.fileinputstream.uuidcache.config;

import de.fileinputstream.uuidcache.UUIDCacheBootstrap;

import java.io.*;
import java.util.Properties;

/**
 * This class has been generated by Alexander on 29.04.18 22:03
 * You are not allowed to edit this resource or other components of it
 * © 2018 Alexander Fiedler
 */
public class UUIDConfig {

    final File configFile = new File(UUIDCacheBootstrap.getInstance().getDataFolder(),"apiConfig.properties");
    Properties properties = new Properties();

    public void writeConfigFile() {
        try {
            properties.load(new FileInputStream(configFile));
            properties.setProperty("RabbitHost","127.0.0.1");
            properties.store(new FileOutputStream(configFile),"");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
